version: '3.8'

services:
  flask-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./omrdata:/app/data
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1